In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

In [2]:
file_path = '../../datasets/b3_dados/processed/acoes_concat.csv'
acoes_data = pd.read_csv(file_path)

In [3]:
acoes_data

,Date,ITUB4,BBAS3,CYRE3,TEND3,DIRR3,ELET3,EQTL3,CMIG4,PETR3,VALE3,BRAP3
0,2010-01-04,10.562274,5.562300,14.371702,5.135384,5.177327,20.123955,2.727207,1.917287,11.676325,23.756481,3.748754
1,2010-01-05,10.630730,5.506486,14.235113,5.089202,5.154717,19.958874,2.748718,1.946624,11.606239,23.977951,3.767592
2,2010-01-06,10.538581,5.513929,14.252928,5.089202,5.109501,19.703260,2.719525,1.909956,11.721180,24.485470,3.805269
3,2010-01-07,10.430645,5.515787,13.979749,5.061493,5.154717,20.161232,2.688796,1.891619,11.651093,24.586971,3.852364
4,2010-01-08,10.272685,5.547416,13.955992,4.950658,5.163762,20.502045,2.728743,1.889784,11.564186,24.826887,3.899458
...,...,...,...,...,...,...,...,...,...,...,...,...
3158,2022-09-23,24.634073,17.513254,15.503020,7.171067,12.927425,44.050091,26.192175,6.683025,19.150974,58.827377,16.100027
3159,2022-09-26,24.103085,16.782280,14.975771,6.987441,12.427061,42.688801,25.939671,6.806203,18.906494,58.956070,16.168182
3160,2022-09-27,23.963816,16.571592,14.864769,6.832809,12.304021,41.461727,25.395823,6.219857,19.133511,58.080986,16.024296
3161,2022-09-28,23.955107,16.575890,16.076519,6.910125,12.681343,40.876949,25.347263,6.133631,18.999628,58.630054,16.062159
3162,2022-09-29,24.311991,16.485590,15.956271,6.919790,12.935627,40.713982,25.259859,6.064649,19.017090,58.707272,15.978860